#!/usr/bin/env python3
"""Build hybrid EdenChat lorebooks for non-branchable routing classes."""

from __future__ import annotations

import io
import json
import os
import shutil
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generate_prompt_lite import MANUAL_LITE_PATCHES
from prompt_lite_utils import (
    LITE_ROOT,
    SOURCE_ROOT,
    compact_dialogue_example,
    compact_label_part,
    compact_text,
    contains_string,
    extract_protected_literals,
    is_protected,
    load_prompt,
    parse_keywords,
    path_label,
    sentence_budget,
    sha256_file,
    write_prompt,
)

if sys.stdout.encoding != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")
os.environ.setdefault("PYTHONIOENCODING", "utf-8")


PROJECT_ROOT = Path(__file__).resolve().parent.parent
PROMPTS_ROOT = PROJECT_ROOT / "docs" / "prompts"
CLASSIFIED_MANIFEST = PROMPTS_ROOT / "routing_classified" / "manifest.json"
UNIFIED_ROOT = PROMPTS_ROOT / "json_unified"
REPORTS_ROOT = PROMPTS_ROOT / "reports"
UNIFIED_MANIFEST = PROMPTS_ROOT / "unified_manifest.json"
MARKER_FILE = UNIFIED_ROOT / ".generated-by-build-unified-lorebooks"

INTEGRATE_CLASSES = {
    "02_media_format",
    "05_dynamic_character_core",
    "06_dynamic_character_trigger",
    "07_dynamic_deep_context",
    "08_dynamic_world_event",
    "09_ambiguous_review",
}
ROUTEABLE_CLASSES = {
    "03_routeable_fixed_command",
    "04_routeable_state_keyword",
}

EXTRA_BUDGETS = {
    "inner": 320,
    "in": 320,
    "overview": 260,
    "ov": 260,
    "scope_note": 230,
    "scope": 230,
    "trigger_context": 190,
    "ctx": 170,
    "mode_interop": 190,
    "interop": 190,
    "voice": 120,
    "v": 120,
    "rel": 125,
    "relationship": 125,
    "dynamics": 135,
    "dyn": 135,
    "response_patterns": 135,
    "svg_hooks": 120,
    "svg": 120,
    "note": 110,
    "n": 110,
    "condition": 90,
    "cond": 90,
    "trigger": 90,
    "reaction": 120,
    "limit": 90,
    "rule": 105,
    "initial": 105,
    "escalation": 105,
    "behavior": 115,
    "dynamic": 150,
    "baseline": 150,
    "aftermath": 120,
    "after": 120,
    "phase": 120,
    "stage": 120,
}


def load_classified_rows() -> list[dict[str, Any]]:
    manifest = json.loads(CLASSIFIED_MANIFEST.read_text(encoding="utf-8"))
    return list(manifest["entries"])


def reset_unified_root() -> None:
    resolved_output = UNIFIED_ROOT.resolve()
    resolved_prompts = PROMPTS_ROOT.resolve()
    if resolved_prompts not in resolved_output.parents:
        raise RuntimeError(f"refusing output outside prompts root: {resolved_output}")
    if UNIFIED_ROOT.exists():
        if not MARKER_FILE.exists():
            raise RuntimeError(f"refusing to overwrite unmarked directory: {UNIFIED_ROOT}")
        shutil.rmtree(UNIFIED_ROOT)
    UNIFIED_ROOT.mkdir(parents=True)
    MARKER_FILE.write_text(
        "Generated by tools/build_unified_lorebooks.py. Safe to regenerate.\n",
        encoding="utf-8",
    )


def normalize_file_id(file_id: str) -> str:
    return file_id.replace("\\", "/")


def source_path(file_id: str) -> Path:
    return SOURCE_ROOT / Path(file_id)


def lite_path(file_id: str) -> Path:
    return LITE_ROOT / Path(file_id)


def unified_path(file_id: str) -> Path:
    return UNIFIED_ROOT / Path(file_id)


def budget_for_hybrid(parts: tuple[str | int, ...], route_class: str) -> int:
    keys = [str(part) for part in parts if not isinstance(part, int)]
    for key in reversed(keys):
        if key in EXTRA_BUDGETS:
            return EXTRA_BUDGETS[key]
    if route_class == "02_media_format":
        return 95
    if keys and keys[-1] in {"prompt", "description", "desc"}:
        return 150
    return 145


def compact_hybrid_value(parts: tuple[str | int, ...], value: str, route_class: str) -> str:
    text = compact_text(value)
    return sentence_budget(text, budget_for_hybrid(parts, route_class))


def dedupe(items: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        result.append(item)
    return result


def add_scalar_field(
    fields: list[str],
    keeps: list[str],
    parts: tuple[str | int, ...],
    value: str,
    route_class: str,
) -> None:
    if is_protected(parts, value):
        keeps.append(value)
        return
    if "voice" in {str(part) for part in parts if not isinstance(part, int)}:
        value = compact_dialogue_example(value)
    text = compact_hybrid_value(parts, value, route_class)
    label = path_label(parts)
    fields.append(f"{label}:{text}" if label else text)


def add_scalar_list(
    fields: list[str],
    keeps: list[str],
    parts: tuple[str | int, ...],
    values: list[Any],
    route_class: str,
) -> bool:
    if not values or not all(not isinstance(item, (dict, list)) for item in values):
        return False
    key_set = {str(part) for part in parts if not isinstance(part, int)}
    limit = 1 if "voice" in key_set else 6
    compacted: list[str] = []
    for index, item in enumerate(values[:limit]):
        if isinstance(item, str):
            if is_protected((*parts, index), item):
                keeps.append(item)
                continue
            text = compact_dialogue_example(item) if "voice" in key_set else item
            compacted.append(compact_hybrid_value((*parts, index), text, route_class))
        elif item is not None:
            compacted.append(str(item))
    if compacted:
        label = path_label(parts)
        fields.append(f"{label}:{'|'.join(compacted)}" if label else "|".join(compacted))
    return True


def direct_scalar_pairs(
    value: dict[str, Any],
    parts: tuple[str | int, ...],
    keeps: list[str],
    route_class: str,
) -> list[str]:
    pairs: list[str] = []
    for key, child in value.items():
        if key in {"id", "title"}:
            continue
        child_parts = (*parts, key)
        label = compact_label_part(str(key))
        if isinstance(child, str):
            if is_protected(child_parts, child):
                keeps.append(child)
                continue
            text = child
            if "voice" in {str(part) for part in child_parts if not isinstance(part, int)}:
                text = compact_dialogue_example(text)
            pairs.append(f"{label}={compact_hybrid_value(child_parts, text, route_class)}")
        elif isinstance(child, (int, float, bool)):
            pairs.append(f"{label}={child}")
    return pairs


def flatten_hybrid_prompt(data: Any, route_class: str) -> dict[str, Any]:
    fields: list[str] = []
    keeps: list[str] = []

    def walk(value: Any, parts: tuple[str | int, ...] = ()) -> None:
        if isinstance(value, dict):
            pairs = direct_scalar_pairs(value, parts, keeps, route_class)
            if pairs:
                label = path_label(parts)
                fields.append(f"{label}:{'|'.join(pairs)}" if label else "|".join(pairs))
            for key, child in value.items():
                if key in {"id", "title"}:
                    continue
                if isinstance(child, (dict, list)):
                    walk(child, (*parts, key))
            return
        if isinstance(value, list):
            if add_scalar_list(fields, keeps, parts, value, route_class):
                return
            for index, child in enumerate(value):
                walk(child, (*parts, index))
            return
        if isinstance(value, str):
            add_scalar_field(fields, keeps, parts, value, route_class)
            return
        if value is not None:
            label = path_label(parts)
            fields.append(f"{label}:{value}" if label else str(value))

    walk(data)
    output: dict[str, Any] = {"hybrid": ";".join(item for item in fields if item)}
    if keeps:
        output["keep"] = dedupe(keeps)
    return output


def manual_lite_patch(relative_file: str) -> str | None:
    return MANUAL_LITE_PATCHES.get(normalize_file_id(relative_file))


def extract_lite_additions(relative_file: str) -> list[str]:
    patch = manual_lite_patch(relative_file)
    return [patch] if patch else []


def compare_protected_literals(original_data: Any, unified_data: Any) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for item in extract_protected_literals(original_data):
        pointer = item["json_pointer"]
        expected_values = [
            value for path, value in iter_string_values(original_data)
            if json_pointer(path) == pointer
        ]
        expected = expected_values[0] if expected_values else ""
        rows.append(
            {
                "json_pointer": pointer,
                "kind": item["kind"],
                "status": "preserved" if expected and contains_string(unified_data, expected) else "missing",
            }
        )
    return rows


def iter_string_values(data: Any, parts: tuple[str | int, ...] = ()):
    if isinstance(data, dict):
        for key, value in data.items():
            yield from iter_string_values(value, (*parts, key))
    elif isinstance(data, list):
        for index, value in enumerate(data):
            yield from iter_string_values(value, (*parts, index))
    elif isinstance(data, str):
        yield parts, data


def json_pointer(parts: tuple[str | int, ...]) -> str:
    escaped = [str(part).replace("~", "~0").replace("/", "~1") for part in parts]
    return "/" + "/".join(escaped)


def build_unified_data(
    relative_file: str,
    original_data: Any,
    route_class: str,
) -> tuple[dict[str, Any], list[str]]:
    unified = flatten_hybrid_prompt(original_data, route_class)
    additions = extract_lite_additions(relative_file)
    if additions:
        unified["lite_add"] = additions
    return unified, additions


def build() -> dict[str, Any]:
    reset_unified_root()
    rows = load_classified_rows()
    original_rows = [
        row for row in rows
        if row["variant"] == "original" and row["route_class"] in INTEGRATE_CLASSES
    ]
    lite_by_file = {
        row["file"]: row for row in rows
        if row["variant"] == "lite"
    }

    manifest_entries: list[dict[str, Any]] = []
    warnings: list[str] = []

    for row in original_rows:
        file_id = row["file"]
        original_path = source_path(file_id)
        original_data, original_body, original_footer = load_prompt(original_path)
        lite_body = ""
        lite_footer = ""
        lite_source = lite_path(file_id)
        if lite_source.exists():
            _, lite_body, lite_footer = load_prompt(lite_source)
        else:
            warnings.append(f"missing lite pair: {file_id}")

        unified_data, additions = build_unified_data(file_id, original_data, row["route_class"])
        target = unified_path(file_id)
        write_prompt(target, unified_data, original_footer)

        _, unified_body, unified_footer = load_prompt(target)
        original_keywords = parse_keywords(original_footer)
        lite_keywords = parse_keywords(lite_footer)
        unified_keywords = parse_keywords(unified_footer)
        trigger_delta = "same"
        if lite_footer and original_keywords != lite_keywords:
            trigger_delta = "original_footer_used_lite_differs"
            warnings.append(f"trigger mismatch, original footer used: {file_id}")

        literal_rows = compare_protected_literals(original_data, unified_data)
        missing_literals = [item for item in literal_rows if item["status"] != "preserved"]
        if missing_literals:
            warnings.append(f"protected literal missing: {file_id} ({len(missing_literals)})")

        manifest_entries.append(
            {
                "id": normalize_file_id(file_id),
                "index": row["index"],
                "display_name": row["display_name"],
                "category": row["category"],
                "route_class": row["route_class"],
                "strategy": "hybrid_flatten_with_original_footer",
                "source_path": str(original_path.relative_to(PROJECT_ROOT)),
                "lite_path": str(lite_source.relative_to(PROJECT_ROOT)) if lite_source.exists() else None,
                "unified_path": str(target.relative_to(PROJECT_ROOT)),
                "source_sha256": sha256_file(original_path),
                "lite_sha256": sha256_file(lite_source) if lite_source.exists() else None,
                "unified_sha256": sha256_file(target),
                "trigger_delta": trigger_delta,
                "keyword_count": len(unified_keywords),
                "keyword_sample": unified_keywords[:8],
                "protected_literals": literal_rows,
                "manual_lite_additions": additions,
                "chars": {
                    "original": len(original_body),
                    "lite": len(lite_body) if lite_body else None,
                    "unified": len(unified_body),
                },
                "compression": {
                    "vs_original": round(1 - (len(unified_body) / len(original_body)), 4) if original_body else 0,
                    "vs_lite": round(1 - (len(unified_body) / len(lite_body)), 4) if lite_body else None,
                },
                "warnings": [item for item in warnings if item.endswith(file_id)],
            }
        )

    by_class = Counter(entry["route_class"] for entry in manifest_entries)
    total_original = sum(entry["chars"]["original"] for entry in manifest_entries)
    total_lite = sum(entry["chars"]["lite"] or 0 for entry in manifest_entries)
    total_unified = sum(entry["chars"]["unified"] for entry in manifest_entries)
    manifest = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "purpose": "Hybrid single lorebooks for non-branchable original/lite routing classes.",
        "source_roots": {
            "original": "docs/prompts/json",
            "lite": "docs/prompts/json_lite",
            "unified": "docs/prompts/json_unified",
        },
        "policy": {
            "excluded_route_classes": sorted(["00_main_toggle", "01_common_shared", *ROUTEABLE_CLASSES]),
            "integrated_route_classes": sorted(INTEGRATE_CLASSES),
            "footer_policy": "Use original trigger footer; report if lite footer differs.",
            "format_policy": "Preserve protected output-format/url/template strings exactly under keep.",
        },
        "summary": {
            "count": len(manifest_entries),
            "by_route_class": dict(sorted(by_class.items())),
            "chars": {
                "original": total_original,
                "lite": total_lite,
                "unified": total_unified,
            },
            "compression_vs_original": round(1 - (total_unified / total_original), 4) if total_original else 0,
            "compression_vs_lite": round(1 - (total_unified / total_lite), 4) if total_lite else None,
            "compression_vs_original_plus_lite": (
                round(1 - (total_unified / (total_original + total_lite)), 4)
                if total_original + total_lite
                else 0
            ),
            "warning_count": len(warnings),
        },
        "warnings": warnings,
        "entries": manifest_entries,
    }
    UNIFIED_MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    write_report(manifest)
    return manifest


def write_report(manifest: dict[str, Any]) -> None:
    REPORTS_ROOT.mkdir(parents=True, exist_ok=True)
    summary = manifest["summary"]
    lines = [
        "# Unified Lorebooks",
        "",
        "분기 가능한 원본/경량 로어북은 유지하고, 병렬 호출 위험이 큰 로어북만 단일 하이브리드본으로 생성했다.",
        "",
        "## Summary",
        "",
        f"- unified count: {summary['count']}",
        f"- original chars: {summary['chars']['original']:,}",
        f"- lite chars: {summary['chars']['lite']:,}",
        f"- unified chars: {summary['chars']['unified']:,}",
        f"- compression vs original: {summary['compression_vs_original']:.1%}",
        f"- compression vs lite: {summary['compression_vs_lite']:.1%}",
        f"- compression vs original+lite pair: {summary['compression_vs_original_plus_lite']:.1%}",
        "",
        "## By Route Class",
        "",
        "| route class | count |",
        "|---|---:|",
    ]
    for route_class, count in summary["by_route_class"].items():
        lines.append(f"| {route_class} | {count} |")
    lines.extend(
        [
            "",
            "## Policy",
            "",
            "- `03_routeable_fixed_command`, `04_routeable_state_keyword`는 원본/경량 분기 대상으로 남겼다.",
            "- `02`, `05`, `06`, `07`, `08`, `09`는 `docs/prompts/json_unified`에서 단일 운영본으로 제공한다.",
            "- 출력 형식, URL 템플릿, 예시는 `keep`에 원문 그대로 보존한다.",
            "- 경량본의 수동 보강 힌트는 `lite_add`로 흡수한다.",
            "",
            "## Clipboard Usage",
            "",
            "양쪽 프롬프트를 모두 운영할 때는 공유 통합본을 한 번만 넣고, 분기 가능본만 variant별로 넣는다.",
            "",
            "```powershell",
            "python tools\\edenchat_clipboard.py --variant original --mix unified --route-scope shared",
            "python tools\\edenchat_clipboard.py --variant original --mix unified --route-scope branchable",
            "python tools\\edenchat_clipboard.py --variant lite --mix unified --route-scope branchable",
            "```",
            "",
            "단일 variant만 테스트할 때는 아래처럼 전체 세트를 넣을 수 있다.",
            "",
            "```powershell",
            "python tools\\edenchat_clipboard.py --variant original --mix unified --route-scope all",
            "python tools\\edenchat_clipboard.py --variant lite --mix unified --route-scope all",
            "```",
            "",
        ]
    )
    if manifest["warnings"]:
        lines.extend(["## Warnings", ""])
        for warning in manifest["warnings"]:
            lines.append(f"- {warning}")
        lines.append("")
    (REPORTS_ROOT / "unified-lorebooks.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    manifest = build()
    summary = manifest["summary"]
    print(f"generated unified entries: {summary['count']}")
    print(
        "chars: "
        f"original={summary['chars']['original']:,} "
        f"lite={summary['chars']['lite']:,} "
        f"unified={summary['chars']['unified']:,}"
    )
    print(f"compression vs original: {summary['compression_vs_original']:.1%}")
    print(f"manifest: {UNIFIED_MANIFEST}")


if __name__ == "__main__":
    main()
