#!/usr/bin/env python3
"""Classify EdenChat lorebooks by routing risk and mirror them into review dirs."""

from __future__ import annotations

import io
import json
import os
import re
import shutil
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

import edenchat_clipboard

if sys.stdout.encoding != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")
os.environ.setdefault("PYTHONIOENCODING", "utf-8")


PROJECT_ROOT = Path(__file__).resolve().parent.parent
PROMPTS_ROOT = PROJECT_ROOT / "docs" / "prompts"
OUTPUT_ROOT = PROMPTS_ROOT / "routing_classified"
MARKER_FILE = OUTPUT_ROOT / ".generated-by-lorebook-routing"

CLASS_LABELS = {
    "00_main_toggle": "메인 토글",
    "01_common_shared": "공통 단일본",
    "02_media_format": "출력/미디어 양식",
    "03_routeable_fixed_command": "고정 명령 라우팅",
    "04_routeable_state_keyword": "상태/이모지 라우팅",
    "05_dynamic_character_core": "동적 캐릭터 본체",
    "06_dynamic_character_trigger": "동적 캐릭터 트리거",
    "07_dynamic_deep_context": "동적 심화/관계/특수",
    "08_dynamic_world_event": "동적 세계관/이벤트",
    "09_ambiguous_review": "검토 필요",
}

RECOMMENDATIONS = {
    "toggle_pair": "원본/경량 메인 프롬프트 토글로만 운용",
    "shared_single": "원본/경량 구분 없이 단일 공통본으로 운용",
    "route_split_possible": "원본/경량 키워드 분기 가능",
    "unify_or_choose_one": "병렬 삽입 위험. 단일 운영본으로 통합하거나 하나만 선택",
    "needs_review": "혼합 키워드. 실제 세션 샘플로 수동 검토",
}

CHARACTER_CORE_CATEGORIES = {"캐릭터 본체"}
CHARACTER_TRIGGER_CATEGORIES = {"캐릭터 트리거"}
STATE_CATEGORIES = {"캐릭터 초기", "캐릭터 심화", "캐릭터 NSFW"}
DEEP_CONTEXT_CATEGORIES = {"캐릭터 관계", "캐릭터 특수", "캐릭터 씬"}
FIXED_COMMAND_CATEGORIES = {"오디션", "프리플레이", "모드"}
WORLD_EVENT_CATEGORIES = {"구역", "세계관", "이벤트"}
MEDIA_CATEGORIES = {"SVG", "이미지"}

COMMAND_RE = re.compile(r"^[!！/][^\s]+")
ROUND_RE = re.compile(r"^(?:[0-9]+R|[0-9]+R[-_A-Z]*|막간|오디션|대표|매니저|배우|연습생|작곡가|인플루언서|프리플레이|비하인드|소꿉친구|스킵|디테일)")
EMOJI_RE = re.compile(r"[\U0001F000-\U0001FAFF\u2600-\u27BF]")
STATE_RE = re.compile(r"(?:❤️|🔞|호감도|퇴장|등급|라운드|R[_\\-]?)")


def reset_output_dir() -> None:
    resolved_output = OUTPUT_ROOT.resolve()
    resolved_prompts = PROMPTS_ROOT.resolve()
    if resolved_prompts not in resolved_output.parents:
        raise RuntimeError(f"refusing output outside prompts root: {resolved_output}")
    if OUTPUT_ROOT.exists():
        if not MARKER_FILE.exists():
            raise RuntimeError(f"refusing to overwrite unmarked directory: {OUTPUT_ROOT}")
        shutil.rmtree(OUTPUT_ROOT)
    OUTPUT_ROOT.mkdir(parents=True)
    MARKER_FILE.write_text(
        "Generated by tools/classify_lorebook_routes.py. Safe to regenerate.\n",
        encoding="utf-8",
    )


def keyword_type(keyword: str) -> str:
    value = keyword.strip()
    if not value:
        return "empty"
    if COMMAND_RE.search(value):
        return "fixed_command"
    if STATE_RE.search(value):
        return "state_keyword"
    if EMOJI_RE.search(value):
        return "fixed_emoji"
    if ROUND_RE.search(value):
        return "fixed_mode_phrase"
    if len(value) <= 4 and re.fullmatch(r"[가-힣A-Za-z0-9_.-]+", value):
        return "short_name"
    if re.search(r"[?？]|\\s", value):
        return "natural_phrase"
    return "lexical_phrase"


def keyword_profile(keywords: list[str]) -> dict[str, Any]:
    counts = Counter(keyword_type(keyword) for keyword in keywords)
    routeable = sum(counts[key] for key in ("fixed_command", "fixed_emoji", "fixed_mode_phrase", "state_keyword"))
    dynamic = sum(counts[key] for key in ("short_name", "natural_phrase", "lexical_phrase"))
    risk = "low" if dynamic == 0 else "medium" if routeable >= dynamic else "high"
    return {
        "types": dict(sorted(counts.items())),
        "routeable_keyword_count": routeable,
        "dynamic_keyword_count": dynamic,
        "collision_risk": risk,
    }


def classify(entry: dict[str, Any]) -> tuple[str, str]:
    category = entry["category"]
    name = entry["name"]
    profile = keyword_profile(entry["keywords"])

    if category == "메인":
        return "00_main_toggle", "toggle_pair"
    if category == "공통":
        return "01_common_shared", "shared_single"
    if category in MEDIA_CATEGORIES:
        return "02_media_format", "shared_single"
    if category in FIXED_COMMAND_CATEGORIES:
        if profile["dynamic_keyword_count"] and profile["routeable_keyword_count"] == 0:
            return "09_ambiguous_review", "needs_review"
        return "03_routeable_fixed_command", "route_split_possible"
    if category == "나하린":
        if name == "나하린":
            return "05_dynamic_character_core", "unify_or_choose_one"
        if profile["routeable_keyword_count"] >= profile["dynamic_keyword_count"]:
            return "04_routeable_state_keyword", "route_split_possible"
        return "09_ambiguous_review", "needs_review"
    if category in STATE_CATEGORIES:
        if profile["routeable_keyword_count"] >= profile["dynamic_keyword_count"]:
            return "04_routeable_state_keyword", "route_split_possible"
        return "09_ambiguous_review", "needs_review"
    if category in CHARACTER_CORE_CATEGORIES:
        return "05_dynamic_character_core", "unify_or_choose_one"
    if category in CHARACTER_TRIGGER_CATEGORIES:
        return "06_dynamic_character_trigger", "unify_or_choose_one"
    if category in DEEP_CONTEXT_CATEGORIES:
        return "07_dynamic_deep_context", "unify_or_choose_one"
    if category in WORLD_EVENT_CATEGORIES:
        return "08_dynamic_world_event", "unify_or_choose_one"
    return "09_ambiguous_review", "needs_review"


def source_path_for(entry: dict[str, Any], variant: str) -> Path:
    file_id = Path(entry["file"])
    if file_id.parts[:3] == ("docs", "prompts", "common"):
        return PROJECT_ROOT / file_id
    root = edenchat_clipboard.resolve_prompts_dir(variant)
    return root / file_id


def mirror_entry(entry: dict[str, Any], variant: str, route_class: str, index: int) -> str:
    source = source_path_for(entry, variant)
    if not source.exists():
        raise FileNotFoundError(source)
    safe_name = f"{index:03d}__{source.name}"
    target_dir = OUTPUT_ROOT / variant / route_class
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / safe_name
    shutil.copy2(source, target)
    return str(target.relative_to(OUTPUT_ROOT))


def build_variant(variant: str) -> list[dict[str, Any]]:
    entries = edenchat_clipboard.collect_lorebooks(edenchat_clipboard.resolve_prompts_dir(variant))
    rows: list[dict[str, Any]] = []
    for index, entry in enumerate(entries, 1):
        route_class, recommendation = classify(entry)
        profile = keyword_profile(entry["keywords"])
        copied_to = mirror_entry(entry, variant, route_class, index)
        rows.append(
            {
                "variant": variant,
                "index": index,
                "display_name": entry["name"],
                "file": entry["file"],
                "category": entry["category"],
                "route_class": route_class,
                "route_class_label": CLASS_LABELS[route_class],
                "recommendation": recommendation,
                "recommendation_label": RECOMMENDATIONS[recommendation],
                "keyword_count": len(entry["keywords"]),
                "keyword_profile": profile,
                "keywords": entry["keywords"],
                "size": entry["size"],
                "copied_to": copied_to,
            }
        )
    return rows


def write_reports(rows: list[dict[str, Any]]) -> None:
    manifest = {
        "schema_version": 1,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "purpose": "Classify lorebooks by original/lite routing risk without moving source files.",
        "variants": ["original", "lite"],
        "classes": CLASS_LABELS,
        "recommendations": RECOMMENDATIONS,
        "entries": rows,
    }
    (OUTPUT_ROOT / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    counts: dict[str, Counter[str]] = defaultdict(Counter)
    class_recommendations: dict[tuple[str, str], Counter[str]] = defaultdict(Counter)
    for row in rows:
        counts[row["variant"]][row["route_class"]] += 1
        class_recommendations[(row["variant"], row["route_class"])][row["recommendation"]] += 1

    lines = [
        "# Lorebook Routing Classification",
        "",
        "원본/경량 로어북 원본 파일은 이동하지 않았다. 이 디렉토리는 라우팅 설계 검토용 복사본이다.",
        "",
        "## 분류 기준",
        "",
        "- `00_main_toggle`: EdenChat 분리 프롬프트에서 원본/경량 토글 대상.",
        "- `01_common_shared`: 원본/경량 구분 없이 단일본으로 유지할 공통 규칙.",
        "- `02_media_format`: 출력 양식/미디어 규칙. 중복 호출보다 공통 단일본 후보.",
        "- `03_routeable_fixed_command`: `!명령어`, 라운드/모드 고정 토큰 중심. 원본/경량 키워드 분기 가능.",
        "- `04_routeable_state_keyword`: 하트/상태/이모지 조건 중심. 원본/경량 상태 키워드 분기 가능.",
        "- `05`~`08`: 자연어·캐릭터명·관계·세계관 중심. 병렬 삽입 시 중복 호출 위험이 높아 단일 운영본 후보.",
        "- `09_ambiguous_review`: 자동 분류로 결론 내기 어려운 혼합 키워드.",
        "",
        "## 요약",
        "",
        "| variant | route class | count | recommendation |",
        "|---|---|---:|---|",
    ]
    for variant in ("original", "lite"):
        for route_class, count in sorted(counts[variant].items()):
            recs = ", ".join(
                f"{RECOMMENDATIONS[key]}:{value}"
                for key, value in sorted(class_recommendations[(variant, route_class)].items())
            )
            lines.append(f"| {variant} | {route_class} | {count} | {recs} |")
    lines.extend(
        [
            "",
            "## 다음 판단",
            "",
            "- `03_routeable_fixed_command`, `04_routeable_state_keyword`는 원본/경량 접두 키워드 또는 메인 프롬프트 상태 출력 규칙으로 분기 설계 가능.",
            "- `05_dynamic_character_core`, `06_dynamic_character_trigger`, `07_dynamic_deep_context`, `08_dynamic_world_event`는 병렬 호출 방지 대상. 하이브리드 단일본 또는 한쪽 운영본 선택이 필요.",
            "- `02_media_format`은 원본/경량으로 나눌 실익보다 단일 공통본 유지가 안정적.",
            "",
        ]
    )
    (OUTPUT_ROOT / "README.md").write_text("\n".join(lines), encoding="utf-8")

    ambiguous = [
        row for row in rows
        if row["variant"] == "original" and row["route_class"] == "09_ambiguous_review"
    ]
    review_lines = [
        "# Ambiguous Lorebook Review",
        "",
        "원본 기준 검토 필요 항목이다. 경량본은 같은 index/name으로 대칭 복사되어 있다.",
        "",
        "| index | category | name | keyword types | keyword sample |",
        "|---:|---|---|---|---|",
    ]
    for row in ambiguous:
        types = ", ".join(f"{key}:{value}" for key, value in row["keyword_profile"]["types"].items())
        sample = ", ".join(row["keywords"][:6])
        review_lines.append(
            f"| {row['index']} | {row['category']} | {row['display_name']} | {types} | {sample} |"
        )
    review_lines.append("")
    (OUTPUT_ROOT / "ambiguous_review.md").write_text("\n".join(review_lines), encoding="utf-8")


def main() -> None:
    reset_output_dir()
    # During regeneration the previous routing manifest has just been removed.
    # The classifier computes route classes itself, so clipboard collection must
    # not require a stale manifest to exist.
    edenchat_clipboard._ROUTE_CLASS_MAP = {}
    rows = build_variant("original") + build_variant("lite")
    write_reports(rows)
    print(f"classified entries: {len(rows)}")
    print(f"output: {OUTPUT_ROOT}")


if __name__ == "__main__":
    main()
